=== B-Zakaria-u/TechManagment-CRM/Light Management Backend/src/schemas/clients.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="clients">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="client" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="reference" type="xs:string"/>
              <xs:element name="type" type="xs:string"/>
              <xs:element name="raisonSociale" type="xs:string"/>
              <xs:element name="siret" type="xs:string" minOccurs="0"/>
              <xs:element name="formeJuridique" type="xs:string" minOccurs="0"/>
              <xs:element name="effectif" type="xs:integer" minOccurs="0"/>
              <xs:element name="secteurActivite" type="xs:string" minOccurs="0"/>
              
              <xs:element name="adresseFacturation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="adresse" type="xs:string"/>
                    <xs:element name="codePostal" type="xs:string"/>
                    <xs:element name="ville" type="xs:string"/>
                    <xs:element name="pays" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="contacts">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="contact" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nom" type="xs:string"/>
                          <xs:element name="prenom" type="xs:string"/>
                          <xs:element name="fonction" type="xs:string"/>
                          <xs:element name="email" type="xs:string"/>
                          <xs:element name="telephone" type="xs:string"/>
                          <xs:element name="statut" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="informationsCommerciales">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="source" type="xs:string"/>
                    <xs:element name="dateAcquisition" type="xs:date"/>
                    <xs:element name="commercialResponsable" type="xs:string"/>
                    <xs:element name="niveau" type="xs:string"/>
                    <xs:element name="chiffreAffaireCumule" type="xs:decimal"/>
                    <xs:element name="dernierAchat" type="xs:date"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="contrats" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="contrat" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="reference" type="xs:string"/>
                          <xs:element name="type" type="xs:string"/>
                          <xs:element name="dateDebut" type="xs:date"/>
                          <xs:element name="dateFin" type="xs:date"/>
                          <xs:element name="montant" type="xs:decimal"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== B-Zakaria-u/TechManagment-CRM/data/clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/zakar/Desktop/Bozari%20Zakaria%20-%20TP%203%20Cloud/schemas/clients.xsd">
  <client id="C1000">
    <reference>CLI-2024-001</reference>
    <type>ENTREPRISE</type>
    <raisonSociale>Société Data Analytics</raisonSociale>
    <siret>92864031749641</siret>
    <formeJuridique>SNC</formeJuridique>
    <effectif>411</effectif>
    <secteurActivite>FINANCE</secteurActivite>
    <adresseFacturation>
      <adresse>161 Place de la Concorde</adresse>
      <codePostal>14357</codePostal>
      <ville>Le Havre</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Martin</nom>
        <prenom>Chantal</prenom>
        <fonction>Responsable Achats</fonction>
        <email>chantal.martin@sociétédataanalytics.fr</email>
        <telephone>+33746016504</telephone>
        <statut>PRESCRIPTEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>PROSPECTION</source>
      <dateAcquisition>2023-01-18</dateAcquisition>
      <commercialResponsable>U1019</commercialResponsable>
      <niveau>CLIENT</niveau>
      <chiffreAffaireCumule>41337.26</chiffreAffaireCumule>
      <dernierAchat>2024-01-23</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-001</reference>
        <type>DEVELOPPEMENT</type>
        <dateDebut>2024-02-20</dateDebut>
        <dateFin>2025-11-24</dateFin>
        <montant>25442.04</montant>
      </contrat>
    </contrats>
  </client>
  <client id="C1001">
    <reference>CLI-2024-002</reference>
    <type>ENTREPRISE</type>
    <raisonSociale>Société Future Systems</raisonSociale>
    <siret>79274289873921</siret>
    <formeJuridique>SARL</formeJuridique>
    <effectif>266</effectif>
    <secteurActivite>FINANCE</secteurActivite>
    <adresseFacturation>
      <adresse>162 Rue Lafayette</adresse>
      <codePostal>65531</codePostal>
      <ville>Montpellier</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Lambert</nom>
        <prenom>Céline</prenom>
        <fonction>CEO</fonction>
        <email>céline.lambert@sociétéfuturesystems.fr</email>
        <telephone>+33974395395</telephone>
        <statut>UTILISATEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>SALON</source>
      <dateAcquisition>2023-11-12</dateAcquisition>
      <commercialResponsable>U1005</commercialResponsable>
      <niveau>CLIENT_VIP</niveau>
      <chiffreAffaireCumule>422175.22</chiffreAffaireCumule>
      <dernierAchat>2024-07-29</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-002</reference>
        <type>MAINTENANCE</type>
        <dateDebut>2024-01-04</dateDebut>
        <dateFin>2025-09-11</dateFin>
        <montant>42344.94</montant>
      </contrat>
    </contrats>
  </client>
  <client id="C1002">
    <reference>CLI-2024-003</reference>
    <type>ENTREPRISE</type>
    <raisonSociale>Société Cloud Masters</raisonSociale>
    <siret>98044549311264</siret>
    <formeJuridique>SAS</formeJuridique>
    <effectif>314</effectif>
    <secteurActivite>SSII</secteurActivite>
    <adresseFacturation>
      <adresse>170 Avenue Montaigne</adresse>
      <codePostal>95930</codePostal>
      <ville>Marseille</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Perrin</nom>
        <prenom>Pascal</prenom>
        <fonction>Directeur IT</fonction>
        <email>pascal.perrin@sociétécloudmasters.fr</email>
        <telephone>+33953933182</telephone>
        <statut>PRESCRIPTEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>RECOMMANDATION</source>
      <dateAcquisition>2023-06-29</dateAcquisition>
      <commercialResponsable>U1013</commercialResponsable>
      <niveau>CLIENT_VIP</niveau>
      <chiffreAffaireCumule>200085.19</chiffreAffaireCumule>
      <dernierAchat>2024-04-08</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-003</reference>
        <type>DEVELOPPEMENT</type>
        <dateDebut>2024-03-02</dateDebut>
        <dateFin>2025-08-26</dateFin>
        <montant>35990.07</montant>
      </contrat>
    </contrats>
  </client>
  <client id="C1003">
    <reference>CLI-2024-004</reference>
    <type>ENTREPRISE</type>
    <raisonSociale>Société Agile Team</raisonSociale>
    <siret>94133711665895</siret>
    <formeJuridique>EURL</formeJuridique>
    <effectif>450</effectif>
    <secteurActivite>E-COMMERCE</secteurActivite>
    <adresseFacturation>
      <adresse>177 Boulevard Haussmann</adresse>
      <codePostal>72876</codePostal>
      <ville>Lille</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Muller</nom>
        <prenom>Corinne</prenom>
        <fonction>CTO</fonction>
        <email>corinne.muller@sociétéagileteam.fr</email>
        <telephone>+33358057387</telephone>
        <statut>UTILISATEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>WEB</source>
      <dateAcquisition>2023-11-27</dateAcquisition>
      <commercialResponsable>U1012</commercialResponsable>
      <niveau>PROSPECT</niveau>
      <chiffreAffaireCumule>122834.43</chiffreAffaireCumule>
      <dernierAchat>2024-01-08</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-004</reference>
        <type>SUPPORT</type>
        <dateDebut>2024-03-13</dateDebut>
        <dateFin>2025-02-22</dateFin>
        <montant>45260.54</montant>
      </contrat>
    </contrats>
  </client>
  <client id="C1004">
    <reference>CLI-2024-005</reference>
    <type>PARTICULIER</type>
    <raisonSociale>Société Cloud Systems</raisonSociale>
    <siret>42664965802358</siret>
    <formeJuridique>EURL</formeJuridique>
    <effectif>251</effectif>
    <secteurActivite>FINANCE</secteurActivite>
    <adresseFacturation>
      <adresse>96 Rue Victor Hugo</adresse>
      <codePostal>24886</codePostal>
      <ville>Lille</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Robin</nom>
        <prenom>Nathalie</prenom>
        <fonction>CTO</fonction>
        <email>nathalie.robin@sociétécloudsystems.fr</email>
        <telephone>+33736067702</telephone>
        <statut>DECIDEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>PARTENAIRE</source>
      <dateAcquisition>2023-02-06</dateAcquisition>
      <commercialResponsable>U1014</commercialResponsable>
      <niveau>CLIENT_VIP</niveau>
      <chiffreAffaireCumule>355087.59</chiffreAffaireCumule>
      <dernierAchat>2024-09-18</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-005</reference>
        <type>MAINTENANCE</type>
        <dateDebut>2024-04-28</dateDebut>
        <dateFin>2024-09-02</dateFin>
        <montant>11599.51</montant>
      </contrat>
    </contrats>
  </client>
  <client id="C1005">
    <reference>CLI-2024-006</reference>
    <type>ENTREPRISE</type>
    <raisonSociale>Société IT Partners</raisonSociale>
    <siret>19463288462400</siret>
    <formeJuridique>EURL</formeJuridique>
    <effectif>91</effectif>
    <secteurActivite>SSII</secteurActivite>
    <adresseFacturation>
      <adresse>44 Rue Lafayette</adresse>
      <codePostal>28922</codePostal>
      <ville>Saint-Étienne</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Nicolas</nom>
        <prenom>Michel</prenom>
        <fonction>Directeur IT</fonction>
        <email>michel.nicolas@sociétéitpartners.fr</email>
        <telephone>+33568501708</telephone>
        <statut>PRESCRIPTEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>WEB</source>
      <dateAcquisition>2024-06-12</dateAcquisition>
      <commercialResponsable>U1004</commercialResponsable>
      <niveau>PROSPECT</niveau>
      <chiffreAffaireCumule>42788.77</chiffreAffaireCumule>
      <dernierAchat>2024-08-17</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-006</reference>
        <type>DEVELOPPEMENT</type>
        <dateDebut>2024-03-15</dateDebut>
        <dateFin>2025-05-04</dateFin>
        <montant>21735.91</montant>
      </contrat>
    </contrats>
  </client>
  <client id="C1006">
    <reference>CLI-2024-007</reference>
    <type>ENTREPRISE</type>
    <raisonSociale>Société Tech Solutions</raisonSociale>
    <siret>26460035026836</siret>
    <formeJuridique>EURL</formeJuridique>
    <effectif>439</effectif>
    <secteurActivite>INDUSTRIE</secteurActivite>
    <adresseFacturation>
      <adresse>3 Avenue des Champs-Élysées</adresse>
      <codePostal>84740</codePostal>
      <ville>Reims</ville>
      <pays>France</pays>
    </adresseFacturation>
    <contacts>
      <contact>
        <nom>Girard</nom>
        <prenom>Thierry</prenom>
        <fonction>Directeur IT</fonction>
        <email>thierry.girard@sociététechsolutions.fr</email>
        <telephone>+33221499597</telephone>
        <statut>PRESCRIPTEUR</statut>
      </contact>
    </contacts>
    <informationsCommerciales>
      <source>RECOMMANDATION</source>
      <dateAcquisition>2024-09-07</dateAcquisition>
      <commercialResponsable>U1013</commercialResponsable>
      <niveau>PROSPECT</niveau>
      <chiffreAffaireCumule>229061.82</chiffreAffaireCumule>
      <dernierAchat>2024-08-31</dernierAchat>
    </informationsCommerciales>
    <contrats>
      <contrat>
        <reference>CONT-2024-007</reference>
        <type>LICENCE</type>
        <dateDebut>2024-02-06</dateDebut>
        <dateFin>2025-12-25</dateFin>
