=== B-Zakaria-u/TechManagment-CRM/Light Management Backend/src/schemas/commandes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="commandes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="commande" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="reference" type="xs:string"/>
              <xs:element name="clientId" type="xs:string"/>
              <xs:element name="opportuniteId" type="xs:string" minOccurs="0"/>
              <xs:element name="type" type="xs:string"/>
              <xs:element name="statut" type="xs:string"/>
              <xs:element name="dateCreation" type="xs:date"/>
              <xs:element name="dateValidation" type="xs:date" minOccurs="0"/>
              
              <xs:element name="lignes" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ligne" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="produitId" type="xs:string"/>
                          <xs:element name="quantite" type="xs:integer"/>
                          <xs:element name="prixUnitaireHT" type="xs:decimal"/>
                          <xs:element name="remise" type="xs:decimal"/>
                          <xs:element name="totalHT" type="xs:decimal"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="totaux">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="totalHT" type="xs:decimal"/>
                    <xs:element name="totalTVA" type="xs:decimal"/>
                    <xs:element name="totalTTC" type="xs:decimal"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="conditions" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="delaiLivraison" type="xs:integer"/>
                    <xs:element name="modalitesPaiement" type="xs:string"/>
                    <xs:element name="validiteDevis" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== B-Zakaria-u/TechManagment-CRM/data/commandes.xml
<?xml version="1.0" encoding="UTF-8"?>
<commandes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/zakar/Desktop/Bozari%20Zakaria%20-%20TP%203%20Cloud/schemas/commandes.xsd">
  <!-- <commande id="CMD4000">
    <reference>CMD-2024-001</reference>
    <clientId>CLI-2024-080</clientId>
    <type>FACTURE</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-03-24</dateCreation>
    <dateValidation>2024-10-18</dateValidation>
    <totaux>
      <totalHT>39151.29</totalHT>
      <totalTVA>7830.26</totalTVA>
      <totalTTC>46981.55</totalTTC>
    </totaux>
  </commande> -->
  <commande id="CMD4001">
    <reference>CMD-2024-002</reference>
    <clientId>CLI-2024-093</clientId>
    <type>DEVIS</type>
    <statut>LIVREE</statut>
    <dateCreation>2024-02-06</dateCreation>
    <dateValidation>2024-05-10</dateValidation>
    <totaux>
      <totalHT>22761.24</totalHT>
      <totalTVA>4552.25</totalTVA>
      <totalTTC>27313.49</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4002">
    <reference>CMD-2024-003</reference>
    <clientId>CLI-2024-053</clientId>
    <type>COMMANDE</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-08-27</dateCreation>
    <dateValidation>2024-09-30</dateValidation>
    <totaux>
      <totalHT>25060.14</totalHT>
      <totalTVA>5012.03</totalTVA>
      <totalTTC>30072.17</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4003">
    <reference>CMD-2024-004</reference>
    <clientId>CLI-2024-039</clientId>
    <type>DEVIS</type>
    <statut>VALIDEE</statut>
    <dateCreation>2024-02-18</dateCreation>
    <dateValidation>2024-06-10</dateValidation>
    <totaux>
      <totalHT>21362.05</totalHT>
      <totalTVA>4272.41</totalTVA>
      <totalTTC>25634.46</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4004">
    <reference>CMD-2024-005</reference>
    <clientId>CLI-2024-031</clientId>
    <type>DEVIS</type>
    <statut>VALIDEE</statut>
    <dateCreation>2024-04-30</dateCreation>
    <dateValidation>2024-10-22</dateValidation>
    <totaux>
      <totalHT>21659.16</totalHT>
      <totalTVA>4331.83</totalTVA>
      <totalTTC>25990.99</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4005">
    <reference>CMD-2024-006</reference>
    <clientId>CLI-2024-076</clientId>
    <type>FACTURE</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-04-20</dateCreation>
    <dateValidation>2024-10-06</dateValidation>
    <totaux>
      <totalHT>47683.26</totalHT>
      <totalTVA>9536.65</totalTVA>
      <totalTTC>57219.91</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4006">
    <reference>CMD-2024-007</reference>
    <clientId>CLI-2024-083</clientId>
    <type>FACTURE</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-04-06</dateCreation>
    <dateValidation>2024-04-30</dateValidation>
    <totaux>
      <totalHT>11359.05</totalHT>
      <totalTVA>2271.81</totalTVA>
      <totalTTC>13630.86</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4007">
    <reference>CMD-2024-008</reference>
    <clientId>CLI-2024-018</clientId>
    <type>COMMANDE</type>
    <statut>EN_ATTENTE</statut>
    <dateCreation>2024-08-18</dateCreation>
    <dateValidation>2024-11-20</dateValidation>
    <totaux>
      <totalHT>13362.01</totalHT>
      <totalTVA>2672.40</totalTVA>
      <totalTTC>16034.41</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4008">
    <reference>CMD-2024-009</reference>
    <clientId>CLI-2024-086</clientId>
    <type>COMMANDE</type>
    <statut>VALIDEE</statut>
    <dateCreation>2024-02-17</dateCreation>
    <dateValidation>2024-04-15</dateValidation>
    <totaux>
      <totalHT>9227.37</totalHT>
      <totalTVA>1845.47</totalTVA>
      <totalTTC>11072.84</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4009">
    <reference>CMD-2024-010</reference>
    <clientId>CLI-2024-092</clientId>
    <type>FACTURE</type>
    <statut>EN_ATTENTE</statut>
    <dateCreation>2024-11-24</dateCreation>
    <dateValidation>2024-12-24</dateValidation>
    <totaux>
      <totalHT>41689.31</totalHT>
      <totalTVA>8337.86</totalTVA>
      <totalTTC>50027.17</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4010">
    <reference>CMD-2024-011</reference>
    <clientId>CLI-2024-078</clientId>
    <type>COMMANDE</type>
    <statut>ANNULEE</statut>
    <dateCreation>2024-10-28</dateCreation>
    <dateValidation>2024-12-24</dateValidation>
    <totaux>
      <totalHT>7583.76</totalHT>
      <totalTVA>1516.75</totalTVA>
      <totalTTC>9100.51</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4011">
    <reference>CMD-2024-012</reference>
    <clientId>CLI-2024-090</clientId>
    <type>FACTURE</type>
    <statut>VALIDEE</statut>
    <dateCreation>2024-08-13</dateCreation>
    <dateValidation>2024-12-25</dateValidation>
    <totaux>
      <totalHT>29731.84</totalHT>
      <totalTVA>5946.37</totalTVA>
      <totalTTC>35678.21</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4012">
    <reference>CMD-2024-013</reference>
    <clientId>CLI-2024-024</clientId>
    <type>FACTURE</type>
    <statut>LIVREE</statut>
    <dateCreation>2024-04-13</dateCreation>
    <dateValidation>2024-05-04</dateValidation>
    <totaux>
      <totalHT>31935.50</totalHT>
      <totalTVA>6387.10</totalTVA>
      <totalTTC>38322.60</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4013">
    <reference>CMD-2024-014</reference>
    <clientId>CLI-2024-037</clientId>
    <type>FACTURE</type>
    <statut>LIVREE</statut>
    <dateCreation>2024-03-03</dateCreation>
    <dateValidation>2024-12-07</dateValidation>
    <totaux>
      <totalHT>37614.70</totalHT>
      <totalTVA>7522.94</totalTVA>
      <totalTTC>45137.64</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4014">
    <reference>CMD-2024-015</reference>
    <clientId>CLI-2024-001</clientId>
    <type>COMMANDE</type>
    <statut>ANNULEE</statut>
    <dateCreation>2024-02-15</dateCreation>
    <dateValidation>2024-03-05</dateValidation>
    <totaux>
      <totalHT>9764.44</totalHT>
      <totalTVA>1952.89</totalTVA>
      <totalTTC>11717.33</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4015">
    <reference>CMD-2024-016</reference>
    <clientId>CLI-2024-081</clientId>
    <type>DEVIS</type>
    <statut>LIVREE</statut>
    <dateCreation>2024-10-05</dateCreation>
    <dateValidation>2024-11-02</dateValidation>
    <totaux>
      <totalHT>12705.23</totalHT>
      <totalTVA>2541.05</totalTVA>
      <totalTTC>15246.28</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4016">
    <reference>CMD-2024-017</reference>
    <clientId>CLI-2024-060</clientId>
    <type>DEVIS</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-10-22</dateCreation>
    <dateValidation>2024-12-03</dateValidation>
    <totaux>
      <totalHT>29333.35</totalHT>
      <totalTVA>5866.67</totalTVA>
      <totalTTC>35200.02</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4017">
    <reference>CMD-2024-018</reference>
    <clientId>CLI-2024-070</clientId>
    <type>DEVIS</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-08-23</dateCreation>
    <dateValidation>2024-10-27</dateValidation>
    <totaux>
      <totalHT>1156.94</totalHT>
      <totalTVA>231.39</totalTVA>
      <totalTTC>1388.33</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4018">
    <reference>CMD-2024-019</reference>
    <clientId>CLI-2024-081</clientId>
    <type>FACTURE</type>
    <statut>EN_COURS</statut>
    <dateCreation>2024-08-08</dateCreation>
    <dateValidation>2024-10-24</dateValidation>
    <totaux>
      <totalHT>3023.60</totalHT>
      <totalTVA>604.72</totalTVA>
      <totalTTC>3628.32</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4019">
    <reference>CMD-2024-020</reference>
    <clientId>CLI-2024-043</clientId>
    <type>COMMANDE</type>
    <statut>ANNULEE</statut>
    <dateCreation>2024-10-06</dateCreation>
    <dateValidation>2024-12-22</dateValidation>
    <totaux>
      <totalHT>14290.32</totalHT>
      <totalTVA>2858.06</totalTVA>
      <totalTTC>17148.38</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4020">
    <reference>CMD-2024-021</reference>
    <clientId>CLI-2024-079</clientId>
    <type>COMMANDE</type>
    <statut>LIVREE</statut>
    <dateCreation>2024-02-17</dateCreation>
    <dateValidation>2024-07-23</dateValidation>
    <totaux>
      <totalHT>38322.23</totalHT>
      <totalTVA>7664.45</totalTVA>
      <totalTTC>45986.68</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4021">
    <reference>CMD-2024-022</reference>
    <clientId>CLI-2024-056</clientId>
    <type>DEVIS</type>
    <statut>EN_ATTENTE</statut>
    <dateCreation>2024-06-11</dateCreation>
    <dateValidation>2024-09-22</dateValidation>
    <totaux>
      <totalHT>21097.02</totalHT>
      <totalTVA>4219.40</totalTVA>
      <totalTTC>25316.42</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4022">
    <reference>CMD-2024-023</reference>
    <clientId>CLI-2024-063</clientId>
    <type>COMMANDE</type>
    <statut>EN_ATTENTE</statut>
    <dateCreation>2024-07-04</dateCreation>
    <dateValidation>2024-10-14</dateValidation>
    <totaux>
      <totalHT>48257.03</totalHT>
      <totalTVA>9651.41</totalTVA>
      <totalTTC>57908.44</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4023">
    <reference>CMD-2024-024</reference>
    <clientId>CLI-2024-006</clientId>
    <type>COMMANDE</type>
    <statut>EN_ATTENTE</statut>
    <dateCreation>2024-07-05</dateCreation>
    <dateValidation>2024-08-07</dateValidation>
    <totaux>
      <totalHT>24398.43</totalHT>
      <totalTVA>4879.69</totalTVA>
      <totalTTC>29278.12</totalTTC>
    </totaux>
  </commande>
  <commande id="CMD4024">
    <reference>CMD-2024-025</reference>
    <clientId>CLI-2024-002</clientId>
    <type>COMMANDE</type>
    <statut>LIVREE</statut>
    <dateCreation>2024-07-22</dateCreation>
    <dateValidation>2024-08-06</dateValidation>
